### ISSUE TITLE
another LaMer gfx/logos-image. 

### ISSUE THREAD

**Issue by ewerybody** [pouetnet/pouet2.0#111]
Hey there! We just had a vacation in France and went hiking around Plateau des Mille Étangs ... however

There was this little village and I had to think of pouet and the logos page :)
So I took this picture: https://i.imgur.com/zLgcuEr.jpg

I see there is no such content here in this repo but maybe someone is interested or knows where that would go?
Cheers! 🍻
ëRiC

![](https://i.imgur.com/zLgcuEr.jpg)

**Comment by Gargaj** [comment]
lol nice

**Comment by Gargaj** [comment]
added
