### ISSUE TITLE
browsers bitching about gfx (?) being delivered unsafe

### ISSUE THREAD

**Issue by Gapstare** [pouetnet/pouet2.0#112]
FF complains that some parts of pouet.net is delivered unsafe. As you know, Google have dictated that this is a big deal. Assuming this is graphics, would changing line 23 to 25 in .htaccess to `https://...` fix this?

**Comment by Gargaj** [comment]
Any specifics? Pouet can embed graphics from external sites.

**Comment by Gapstare** [comment]
Yes, I was just thinking about what shows up on the main page. There's not much there but avatars, prod icons and the logo up top. The "we like" icons seems to be hosted locally too. What type of cat pictures people link to in threads is beyond Pouët's control of course :)

**Comment by Gargaj** [comment]
![image](https://user-images.githubusercontent.com/1702533/128250104-3886149c-13ac-497a-b410-ac3b356f4d31.png)
The front page currently has embedded images from Bitfellas; everything else is HTTPS.
