### ISSUE TITLE
Links in user profile links are broken

### ISSUE THREAD

**Issue by osener** [pouetnet/pouet2.0#116]
All the links in user profile are relative to `/user`, for example `https://www.pouet.net/user.php/prod.php?which=67113` instead of `https://www.pouet.net/prod.php?which=67113`.

[Example profile](https://www.pouet.net/user.php?who=1891)

**Comment by osener** [comment]
My bad, it was because I followed a link to a broken url myself: `https://www.pouet.net/user.php/user.php?who=1891` (from [this](http://www.abductee.org) website). When you visit the correct `/user.php?who=...` address bug does not happen.

**Comment by Gargaj** [comment]
One day we'll get to #45 and fix this.
