### ISSUE TITLE
Show prod id in lists editor

### ISSUE THREAD

**Issue by pulkomandy** [pouetnet/pouet2.0#117]
When adding a prod to a list, you have to find it by title and groupname. There is no way to search by id or even see the prod id.

This is a problem for example when trying to add "68k inside announcement" by "Dekadence" (there are 3 different prods and from the lists menu it's impossible to know which is which)

**Comment by pulkomandy** [comment]
Hello,

A further problem with this:

I am trying to add https://www.pouet.net/prod.php?which=94437 to https://www.pouet.net/lists.php?which=228

I type "Bad Apple" in the search field. Only 10 results are shown. But there are more than 10 demos with this name, and the one I'm looking for does not seem to be in the 10 listed ones.

**Comment by Gargaj** [comment]
![image](https://github.com/pouetnet/pouet2.0/assets/1702533/61078b07-2744-49ac-83ea-fbd3920453fc)
