### ISSUE TITLE
Timestamps for oneliner messages.

### ISSUE THREAD

**Issue by Tomoyapl** [pouetnet/pouet2.0#31]

**Comment by squeakyneb** [comment]
Maybe to the left of the user icon, similar to most IRC clients?

**Comment by Gargaj** [comment]
I thought about that, I'm just not sure the userbase is ready for such a drastic layout change :p

**Comment by Gargaj** [comment]
Look for the customizer option

**Comment by sagamusix** [comment]
Since this new grey color doesn't seem to be used anywhere else in the site, maybe it would be better to use the light blue as used in links? Right now the time color doesn't really seem to fit.

**Comment by Gargaj** [comment]
I don't want to give the impression that they're links. The gray is used on the ordinals on the prod/party/etc pages.
