### ISSUE TITLE
toplist.php

### ISSUE THREAD

**Issue by psenough** [pouetnet/pouet2.0#37]
i miss the old functionality of selecting a time range. to find for example the best prods of a certain year.

i agree the old interface (with two boxes for time range) was not the most intuitive though.

thinking of alternatives, it might be better to have a javascript calendar selection of some sort? with default of starting last month and ending it current day.

also, should toplist.php really be extended to include this functionality? or does it make more sense to create a new .php for that purpose alone?

**Comment by randuev** [comment]
how about we make a sweet simple parameter for get request to toplist.php called "age" that specifies age of the output prods in days. by default age=0, which means you see all prods including very recent ones, posted today. but could say age=365 to get prods that have been released 365 days before and older.

wouldn't that be sweet?

**Comment by Gargaj** [comment]
@psenough There's a temporary solution now: http://www.pouet.net/toplist.php?dateFrom=2015-01-01&dateTo=2015-02-01

@randuev So you mean "age" would be the exact opposite of "days"?

**Comment by randuev** [comment]
well, since there's datefrom/dateto there's no need to implement age at all, but what was meant back then - a way to specify dateto in similar way as datefrom was represented by days )

**Comment by Gargaj** [comment]
I'll just close this as solved then.
