### ISSUE TITLE
Prod edit history prod_change_link shows wrong old value

### ISSUE THREAD

**Issue by minus7** [pouetnet/pouet2.0#51]
The `old` and `new` values both are the new value, e.g. http://www.pouet.net/gloperator_log.php?which=30244&what=prod:
> old: youtube - https://www.youtube.com/watch?v=KMfyrnu3n_c
> new: youtube - https://www.youtube.com/watch?v=KMfyrnu3n_c
> reason: 60FPS 1080p

The old link should be something else (see https://web.archive.org/web/20141011201526/http://www.pouet.net/prod.php?which=30244)

**Comment by Gargaj** [comment]
That's due to old values not being stored. Prolly should fix that.

**Comment by Gargaj** [comment]
I have a local fix already in my working copy, will deploy after a bit more testing.

**Comment by Gargaj** [comment]
Fixed in https://github.com/pouetnet/pouet2.0/commit/92f5af09c1127f982b6e2f2855dfd8818e83100a
