### ISSUE TITLE
Add Demozoo & CSDB id's to submit_modification_request.php

### ISSUE THREAD

**Issue by havoc242** [pouetnet/pouet2.0#59]
Add an extra line to the dropdown selector which takes the user to a page where he can add Demozoo, CSDB and (perhaps, in the future) other ID numbers/codes directly

**Comment by Gargaj** [comment]
I wonder if it would be a better idea to have it automatically submissible like party rankings, bypassing the request system.

**Comment by havoc242** [comment]
I assume that your idea is to add [+demozoo] and [+csdb] links (or something along those lines) to prod.php(?), and only show [+csdb] on C64 prod pages so the page won't get unnecessarily cluttered? I definitely think that's worth a try.

**Comment by Gargaj** [comment]
Fixed in https://github.com/pouetnet/pouet2.0/commit/c525d6191ca86a49647009232d7e499800b9daf9
