### ISSUE TITLE
Merge users [support request / feature request]

### ISSUE THREAD

**Issue by xyproto** [pouetnet/pouet2.0#60]
Hi,

I have two usernames on Pouet, both have the same nick: `Int19h` and the same ICQ number.
The earliest one is registered in 2001, while the one I am using was registered in 2002.
I have no idea why I registered twice, or how it was possible to register twice with the same nick name.

Would it be possible to remove the earliest `Int19h` account, and change the registration date for the second `Int19h` account from 2002-04-29 to 2001-04-29 (which is the date for the earlier account)?

I assume that there are other duplicate nicks in the database, but am not sure if this is best solved as a one-time incident or some sort of merge feature.

Relevant search: http://www.pouet.net/search.php?what=Int19h&type=user

Cheers,
Int19h / Kamelite

**Comment by Gargaj** [comment]
This isn't a Pouet issue (and definitely not an issue with Pouet's code), this is a SceneID issue. The best we can do is to move all data from one account to another.

**Comment by xyproto** [comment]
I see. Sorry if this was reported in the wrong place.

If I could just keep the one with the earliest date (2001-04-29), and reset the password (via rodseth@gmail.com), that would be awesome.

Thanks!

**Comment by Gargaj** [comment]
Any SceneID problem should be forwarded to https://id.scene.org/contact/
