### ISSUE TITLE
Site is not responsive

### ISSUE THREAD

**Issue by pounard** [pouetnet/pouet2.0#63]
Just for fun, posting this, your site is not responsive.

Made me laugh, I randomly found its existence there: https://select2.github.io/examples.html#data-ajax I typed "pouet" for testing, and this repository came first!

**Comment by Gargaj** [comment]
http://m.pouet.net/ is responsive, there has been controversy about the "desktop" site so I opted for two separate domains.

**Comment by DannyCork** [comment]
If a new visitor opens Pouet on a mobile phone it's not responsive. A new visitor doesn't know about this link at the bottom.

I never knew about this link to the mobile version.

To make it better how about Pouet identifies the browser the redirects the user if he or she is using a mobile browser.

**Comment by pounard** [comment]
Fair enough, didn't the link thought.
