### ISSUE TITLE
redirect mobile users to mobile Pouet

### ISSUE THREAD

**Issue by DannyCork** [pouetnet/pouet2.0#64]
mobile internet usage surpassed desktop usage in 2014. Mobile usage is by the dominant internet usage in 2016.

pouet.net is **not** responsive.
m.pouet.net is responsive.

I'd like to suggest that Pouet identifies the client browser the redirects the user to http://m.pouet.net/ if he or she is using a mobile browser.

This can be achieve thus if Pouet runs Apache

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTP_USER_AGENT} "android|blackberry|googlebot-mobile|iemobile|ipad|iphone|ipod|opera mobile|palmos|webos" [NC]
RewriteRule ^$ http://m.example.com/ [L,R=302]
</IfModule>
```

**Comment by Gargaj** [comment]
See https://github.com/pouetnet/pouet2.0/issues/63 - I'm not gonna go through the frustration of arguing with iPhone users again.

**Comment by DannyCork** [comment]
There is no mention of an iPhone in #63 . I've shown how easy this is to achieve and your response is dismissive and vague.

I'll toddle off elsewhere...
