### ISSUE TITLE
Do not cut prod title if adding ellipsis would actually make it same length or longer

### ISSUE THREAD

**Issue by sagamusix** [pouetnet/pouet2.0#83]
![votedis](https://user-images.githubusercontent.com/875883/51943668-64c6a380-241a-11e9-9b48-42d395d73f95.png)

We have accidentally replaced one k by three dots.

(and maybe using an actual ellipsis unicode symbol - i.e. … - would be nicer too.)

**Comment by Gargaj** [comment]
https://github.com/pouetnet/pouet2.0/blob/master/include_generic/functions.inc.php#L175

Not necessarily a fan of Unicode ellipses, because the function can't be sure if the output is HTML or UTF-8.

**Comment by sagamusix** [comment]
If you use `…` rather than `&hellip;` the output format shouldn't make a difference?

**Comment by Gargaj** [comment]
I would need to check the uses; there might be cases where the encoding is expected to be ASCII and not UTF8.
