### ISSUE TITLE
PHP warnings in prod JSON

### ISSUE THREAD

**Issue by sesse** [pouetnet/pouet2.0#84]
Hi,

http://api.pouet.net/v1/prod/?id=80047 contains

`
<br />
<b>Warning</b>:  Use of undefined constant POUETAPI_RATELIMIT_TIMEFRAME - assumed 'POUETAPI_RATELIMIT_TIMEFRAME' (this will throw an Error in a future version of PHP) in <b>/srv/hosted/pouet/sites/api.pouet.net/_rewrite.php</b> on line <b>6</b><br />
<br />
<b>Warning</b>:  Use of undefined constant POUETAPI_RATELIMIT_REQUESTCOUNT - assumed 'POUETAPI_RATELIMIT_REQUESTCOUNT' (this will throw an Error in a future version of PHP) in <b>/srv/hosted/pouet/sites/api.pouet.net/_rewrite.php</b> on line <b>6</b><br />
<br />
<b>Warning</b>:  Use of undefined constant POUETAPI_RATELIMIT_TIMEFRAME - assumed 'POUETAPI_RATELIMIT_TIMEFRAME' (this will throw an Error in a future version of PHP) in <b>/srv/hosted/pouet/sites/api.pouet.net/_rewrite.php</b> on line <b>17</b><br />
`

This breaks the API entirely.

**Comment by Gargaj** [comment]
For future reference, the repo for that is at https://github.com/pouetnet/pouet2.0-api/
